name: Crawling InBody Score

on:
  # push:
  #   branches: [ main ]
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
  
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        submodules: true
    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread
    - name: Crawling Google Spreadsheet
      run: |
        python ./gspread-crawler.py
    - name: Push changes
      run: |
        git add *
        git config --local user.email "ska900222@gmail.com"
        git config --local user.name "HeeamShin"
        git commit -m "GitHub Actions: InBody scores are updated"
        git push